version: "3"
services:
  mongo:
    image: mongo
    restart: unless-stopped

  backend:
    build:
      context: ./meal-diary-backend
      dockerfile: Dockerfile
    environment:
      - AUTH0_CLIENT_ID
      - AUTH0_DOMAIN
      - AUTH0_CLIENT_SECRET
      - AUTH0_AUDIENCE
      - AUTH0_USER_AUDIENCE
      - AUTH0_TEST_AUDIENCE
      - AUTH0_TEST_TOKEN_URL
      - AUTH0_TEST_CLIENT_ID
      - AUTH0_TEST_CLIENT_SECRET
      - AUTH0_TEST_GRANT_TYPE
      - MONGO_URI=mongodb://mongo:27017/<dbname>
      - APP_NAME=local-prod
      - RUN_FINELI_TASK_ON_START=false
      - NODE_ENV=production
      - PORT=4000

  frontend:
    build:
      context: meal-diary-frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:5000
    environment: 
      - NODE_ENV=production