version: "3"
services:
  mongo:
    image: mongo

  backend:
    build:
      context: ../meal-diary-backend
      dockerfile: ../e2e-docker/Dockerfile.backend
    environment:
      - AUTH0_CLIENT_ID
      - AUTH0_DOMAIN
      - AUTH0_CLIENT_SECRET
      - AUDIENCE
      - MONGO_URI=mongodb://localhost:27017/<dbname>
      - APP_NAME=test
      - NODE_ENV=e2e
      - AUTH_STRATEGY=auth0

    depends_on:
      - mongo

  frontend:
    build:
      context: ../meal-diary-frontend
      dockerfile: ../e2e-docker/Dockerfile.frontend
    environment:
      - REACT_APP_AUTH0_CLIENT_ID
      - REACT_APP_AUTH0_DOMAIN
      - REACT_APP_AUTH0_AUDIENCE=${AUDIENCE}

    depends_on:
      - backend

  cypress:
    image: cypress/included:4.9.0
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend
    working_dir: /e2e
    volumes:
      - ../meal-diary-frontend/:/e2e
