version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
  
    volumes:
      - ..:/workspace:cached
      - frontend_node_modules:/workspace/node_modules

    command: sleep infinity
  
volumes:
  frontend_node_modules:

networks:
  default:
    external:
      name: meal-diary