name: Frontend PR

on:
  pull_request:
    branches: ["master"]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Run e2e tests
        env:
          AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
          AUTH0_USER_AUDIENCE: ${{secrets.AUTH0_USER_AUDIENCE}}
          AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
          AUTH0_TEST_TOKEN_URL: ${{secrets.AUTH0_TEST_TOKEN_URL}}
          AUTH0_TEST_CLIENT_ID: ${{secrets.AUTH0_TEST_CLIENT_ID}}
          AUTH0_TEST_CLIENT_SECRET: ${{secrets.AUTH0_TEST_CLIENT_SECRET}}
          AUTH0_TEST_AUDIENCE: ${{secrets.AUTH0_TEST_AUDIENCE}}
          AUTH0_TEST_GRANT_TYPE: ${{secrets.AUTH0_TEST_GRANT_TYPE}}
        run: docker-compose -f ./e2e-docker/docker-compose.yml up --exit-code-from cypress