name: E2E tests

on:
  pull_request:
    branches: ["master"]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-frontend
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('meal-diary-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: npm install
        working-directory: meal-diary-frontend
      - name: Build production app
        run: npm run build
        working-directory: meal-diary-frontend
      - name: Run tests
        run: npm run test:ci
        working-directory: meal-diary-frontend
      - name: Run e2e tests
        env:
          AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
          AUTH0_USER_AUDIENCE: ${{secrets.AUTH0_USER_AUDIENCE}}
          AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
          AUTH0_TEST_TOKEN_URL: ${{secrets.AUTH0_TEST_TOKEN_URL}}
          AUTH0_TEST_CLIENT_ID: ${{secrets.AUTH0_TEST_CLIENT_ID}}
          AUTH0_TEST_CLIENT_SECRET: ${{secrets.AUTH0_TEST_CLIENT_SECRET}}
          AUTH0_TEST_AUDIENCE: ${{secrets.AUTH0_TEST_AUDIENCE}}
          AUTH0_TEST_GRANT_TYPE: ${{secrets.AUTH0_TEST_GRANT_TYPE}}
        run: docker-compose -f ./e2e-docker/docker-compose.yml up --exit-code-from cypress