name: Frontend PR

on:
  pull_request:
    branches: ["master"]
    paths:
      - "meal-diary-frontend/**"

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-frontend
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('meal-diary-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: npm install
        working-directory: meal-diary-frontend
      - name: Run tests
        run: npm run test:ci
        working-directory: meal-diary-frontend
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-frontend
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('meal-diary-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: npm install
        working-directory: meal-diary-frontend
      - name: Run GraphQl code-gen
        run: npm run codegen
        working-directory: meal-diary-frontend
      - name: Run TypeScript compiler
        run: tsc
        working-directory: meal-diary-frontend