name: Frontend Staging

on:
  push:
    branches: ["staging"]
    paths:
      - "meal-diary-frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-frontend
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('meal-diary-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: npm install
        working-directory: meal-diary-frontend
      - name: Create production version
        run: npm run build
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku buildpacks:set https://github.com/hone/heroku-buildpack-static -a meal-diary-frontend-staging
          heroku static:deploy
        working-directory: meal-diary-frontend